- name: OS Specific Tasks
  ansible.builtin.include_tasks: "{{ hostvars[inventory_hostname].ansible_distribution }}.yaml"

- name: Check if OhMyZSH is already installed
  ansible.builtin.stat:
    path: "{{ [ lookup('ansible.builtin.env', 'HOME'), '.oh-my-zsh' ] | path_join }}"
  register: zsh_installed

- name: Download OhMyZSH Install Script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh-install.sh
    mode: '0755'
  when: not zsh_installed.stat.exists

- name: Execute OhMyZSH Install Script
  ansible.builtin.shell: /tmp/ohmyzsh-install.sh --unattended --skip-chsh
  when: not zsh_installed.stat.exists

- name: Install Any Missing ZSH Plugins
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{  [ lookup('ansible.builtin.env', 'HOME'), '.oh-my-zsh', 'custom', 'plugins', item.name] | path_join }}"
  with_items: "{{ zsh_plugins | selectattr('url', 'defined') }}"

- name: Template zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: ~/.zshrc