- name: OS Specific Tasks
  ansible.builtin.include_tasks: "{{ hostvars[inventory_hostname].ansible_distribution }}.yaml"

- name: Install Hack Nerd Font
  block:
    - name: Download Hack Nerd Font
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip
        dest: /tmp/hack-font.zip
    - name: Ensure Font Directory Exists
      file:
        path: "{{ font_dir }}"
        state: directory
    - name: Unpack Hack Font
      unarchive:
        src: /tmp/hack-font.zip
        dest: "{{ font_dir }}"
        remote_src: yes

- name: OS Specific Tasks
  ansible.builtin.include_tasks: "{{ hostvars[inventory_hostname].ansible_distribution }}.yaml"

- name: Check if starship is installed
  ansible.builtin.command: which starship
  environment: 
    PATH: "{{ ansible_env.PATH }}"
  register: starship_installed

# TODO Change Install to OS specific
# MacOS should be installed through brew
- name: Install Starship Prompt
  when: starship_installed.stdout == ""
  block:
    - name: Download Starship Installer Script
      get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship-install.sh
        mode: "u=rwx,g=rwx,o=r"
    - name: Run Starship Install Script
      shell: "sh /tmp/starship-install.sh -y"

- name: Template Starship Config
  template:
    src: starship.toml.j2
    dest: ~/.config/starship.toml