- name: OS Specific Tasks
  ansible.builtin.include_tasks: "{{ hostvars[inventory_hostname].ansible_distribution }}.yaml"

- name: Template Fish Config
  ansible.builtin.template:
    src: config.fish.j2
    dest: ~/.config/fish/config.fish

- name: Template Fish Aliases
  ansible.builtin.template:
    src: aliases.fish.j2
    dest: ~/.config/fish/aliases.fish

- name: Tempalte Fish Functions
  ansible.builtin.template:
    src: functions.fish.j2
    dest: ~/.config/fish/functions.fish
