- name: OS Specific Tasks
  ansible.builtin.include_tasks: "{{ hostvars[inventory_hostname].ansible_distribution }}.yaml"

- name: Set Fish Shell as Default for User
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /opt/homebrew/bin/fish

- name: Template Fish Config
  ansible.builtin.template:
    src: config.fish.j2
    dest: ~/.config/fish/config.fish

- name: Template Fish Aliases
  ansible.builtin.template:
    src: aliases.fish.j2
    dest: ~/.config/fish/aliases.fish

- name: Tempalte Fish Functions
  ansible.builtin.template:
    src: functions.fish.j2
    dest: ~/.config/fish/functions.fish
