- name: MacOS Dependencies
  when: hostvars[inventory_hostname].ansible_distribution == "MacOSX"
  block:
    - name: Check if homebrew is installed
      ansible.builtin.command: command -v brew
      ignore_errors: true
      register: homebrew_installed

    - name: Install Homebrew
      when: homebrew_installed.stdout == ""
      block:
        - name: Download Install Script
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
            dest: /tmp/install-brew
        - name: Run Install Script
          ansible.builtin.shell: bash /tmp/install-brew < /dev/null

- name: Install Fish MacOSX
  when: hostvars[inventory_hostname].ansible_distribution == "MacOSX"
  ansible.builtin.homebrew:
    name: fish
    state: present

- name: Set Fish Shell as Default for User
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /opt/homebrew/bin/fish

- name: Template Fish Config
  template:
    src: fish/config.fish.j2
    dest: ~/.config/fish/config.fish

- name: Template Fish Aliases
  template:
    src: fish/aliases.fish.j2
    dest: ~/.config/fish/aliases.fish

- name: Tempalte Fish Functions
  template:
    src: fish/functions.fish.j2
    dest: ~/.config/fish/functions.fish