shell_aliases:
  ls: exa -al --color=always --group-directories-first --icons
  la: exa -a --color=always --group-directories-first --icons
  ll: exa -l --color=always --group-directories-first --icons
  lt: exa -aT --color=always --group-directories-first --icons
  l.: exa -a | egrep '^\.'
  tarnow: tar -acf 
  untar: tar -zxvf 
  wget: wget -c 
  ..: cd ..
  ...: cd ../..
  ....: cd ../../..
  grep: grep --color=auto
  fgrep: fgrep --color=auto
  egrep: egrep --color=auto
  kc: kubectl
  wkc: watch kubectl

bash_aliases:
  bashup: source $HOME/.bashrc

fish_aliases:
  fishup: source $HOME/.config/fish/config.fish