- name: Install Python3
  ansible.builtin.homebrew:
    name: python

- name: Install NodeJS
  ansible.builtin.homebrew:
    name: node

# TODO Detect architecture
- name: Install GOLANG
  become: true
  block:
    - name: Delete Old GO Versions
      file:
        path: /usr/local/go
        state: absent
    - name: Fetch GO Release
      get_url:
        url: "https://golang.org/dl/go{{ go_version }}.darwin-arm64.tar.gz"
        dest: "/tmp/go.tar.gz"
    - name: Unpack GO
      unarchive:
        src: "/tmp/go.tar.gz"
        dest: /usr/local
        remote_src: true