- name: Install Python3
  become: true
  apt:
    pkg:
      - python3
      - python3-pip

- name: Install NodeJS
  become: true
  apt:
    pkg:
      - nodejs
      - npm

- name: Check for current GO Install
  shell: fish -c "go version"
  register: go_check
  ignore_errors: true

# TODO Detect architecture
- name: Install GOLANG
  become: true
  block:
    - name: Delete Old GO Versions
      file:
        path: /usr/local/go
        state: absent
    - name: Fetch GO Release
      get_url:
        url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/tmp/go.tar.gz"
    - name: Unpack GO
      unarchive:
        src: "/tmp/go.tar.gz"
        dest: /usr/local
        remote_src: true
  when:
    - go_version not in go_check.stdout