- name: Install Hack Nerd Font
  block:
    - name: Download Hack Nerd Font
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip
        dest: /tmp/hack-font.zip
    - name: Ensure Font Directory Exists
      file:
        path: ~/Library/Fonts
        state: directory
    - name: Unpack Hack Font
      unarchive:
        src: /tmp/hack-font.zip
        dest: ~/Library/Fonts
        remote_src: yes

# TODO check if starship is already installed
- name: Install Starship Prompt
  block:
    - name: Download Starship Installer Script
      get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship-install.sh
        mode: "u=rwx,g=rwx,o=r"
    - name: Run Starship Install Script
      shell: "sh /tmp/starship-install.sh -y"

- name: Template Starship Config
  template:
    src: starship.toml.j2
    dest: ~/.config/starship.toml