- name: OS Specific Tasks
  ansible.builtin.include_tasks: "{{ hostvars[inventory_hostname].ansible_distribution }}.yaml"

- name: Template Bashrc
  ansible.builtin.template:
    src: bashrc.j2
    dest: ~/.bashrc

- name: Template Bash Aliases
  ansible.builtin.template:
    src: bash_aliases.j2
    dest: ~/.bash_aliases

- name: Template Bash Functions
  ansible.builtin.template:
    src: bash_functions.j2
    dest: ~/.bash_functions
